language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
  - '6'
before_install:
  - npm install -g codecov
  - pip install --user 'requests[security]'
  - pip install --user -r requirements.txt
script:
  - npm run test
  - npx codecov
  - npm run docs
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local-dir: docs/_build
  on:
    branch: master
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
